### ISSUE TITLE
Pull/Break/etc will not work between users.

### ISSUE THREAD

**Issue by Sansaculotte** [DeadlyBossMods/DBM-Retail#859] opened 2023-02-15 15:36 UTC
**Describe the bug**

When someone use dbm to pull, nothing happend i can't see the countdown
**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by QartemisT** [comment] 2023-02-15 16:25
Can you check if you have this option turned on?

![Untitled](https://user-images.githubusercontent.com/63267788/219089486-1b9e3213-72cb-4db3-8d5f-2d1b2b8a3fbf.png)

**Comment by murdertramp** [comment] 2023-02-15 18:34
I had this same issue and I did not have "Do not show user sent timers (custom/pull/break)" selected in the options.

**Comment by L3n1n** [comment] 2023-02-15 19:51
This is a actual problem after last addon update.

**Comment by MysticalOS** [comment] 2023-02-15 19:56
This is not caused by one of our updates, you could roll back to last version or ANY version of DBM and it's still broken, blizzard made a bad change

**Comment by Mercylas** [comment] 2023-02-15 20:12
This issue looks to apply to all user sent timers - breaks I send/receive are not going through either.

**Comment by MysticalOS** [comment] 2023-02-15 20:20
https://twitter.com/deadlybossmods/status/1625944776590692359

Explanation:

CHAT_MSG_ADDON has several args it returns, one of which is the "sender" (who sent the comm)

this sender up until this week always was Name-realmname, period. Then, addons would call an api called Ambiguate that would automatically translate it to name only for same realm and name-realm for off realm. Then the comm is run through our own local handler.

This week, blizzard started sending only short names. no realm name. Ambiguate function became useless locally since they are already doing it (incorrectly) on server.. Why is it incorrect? because if we don't know realm name of sender we don't even know if sender is off realm or not without performing a bunch of redundant checks such as scanning roster for that name just to check if they are on same realm or not.

"but why realm validate at all?"

because with cross realm groups, it is possible to have two players with same name. In fact that was one of first things I tested. I had two characters with exact same name join a group, and looked at comms from both, and they still both only sent short name with no realm, meaning it wasn't even possible to discern who sent what comm. Even if we scanned entire roster on comm to resolve player names/realms that way, we can't even do that if two exist in raid.

So then that goes to nuclear solution, rewriting comms to now pass a protocol version and our OWN sender arg that still has realmname. this would fix problem but break comms even more until rocky transition is completed with users updating to latest DBM and BW. This is route we'll go though if blizzard doesn't fix it. However I'd like to believe they'll see reason in why this server change is a bad one and revert it so for time being this issue is on hold til we hear back. If we hear back it's intended then prepare for a mandatory DBM update in coming day or two.

**Comment by MysticalOS** [comment] 2023-02-15 20:27
BTW for a list of comms this issue affects

Version check
Pull Timers
Break timers.
Icon elect (which may result in some boss mods no longer setting icons correctly)
Probabably a lot of other less noticable stuff

**Comment by MysticalOS** [comment] 2023-02-16 03:13
new releases have been pushed that fix the issue, in a manner of speaking. The big caveat, there is absolutely 0 backwards compatibility at all with older versions of DBM, or even other addons ATM til they update their comms. For this reason, DBMs addon prefix was entirely changed in all versions of WoW

**Comment by Sansaculotte** [comment] 2023-02-16 14:25
sorry but it still doesnt work even after updated my addon

**Comment by MysticalOS** [comment] 2023-02-16 18:01
It looks like you can get full name from "TARGET" arg

![](https://cdn.discordapp.com/attachments/419696269456572416/1075836325070131260/image.png)

But the rewrite is already done so no sense in reverting it now, it's still more robust/future proofing

**Comment by MysticalOS** [comment] 2023-02-18 21:19
Closing as fixed

**Closed by MysticalOS** 2023-02-18 21:19 UTC
Labels: question, ⚠️ High Priority

**Comment by OricCZE** [comment] 2023-05-20 09:56
@MysticalOS hi can you rework DBM for MoP too? I cant see pull / break timer when im raid leader :/ but if im not in part i see it - where can be problem?

**Comment by QartemisT** [comment] 2023-05-20 09:57
> @MysticalOS hi can you rework DBM for MoP too? I cant see pull / break timer when im raid leader :/ but if im not in part i see it - where can be problem?

We do not support private server builds of DBM.

**Comment by OricCZE** [comment] 2023-05-20 09:59
> > @MysticalOS hi can you rework DBM for MoP too? I cant see pull / break timer when im raid leader :/ but if im not in part i see it - where can be problem?
> 
> We do not support private server builds of DBM.

OU :/ DBM is goo addon but on cta work corectly and n MoP no :/ i dont want switch to tohr :/
