### ISSUE TITLE
Tindral LUA error in Heroic (and LFR per one guild members report)

### ISSUE THREAD

**Issue by 1Drome** [DeadlyBossMods/DBM-Retail#984] opened 2024-01-18 18:46 UTC
**Describe the bug**

When on the Second and Third platform a LUA error would pop up every several seconds during phases of the fight.  I didnt have a bug tracker and was trying to go through the fight so I was quickly dismissing the window (which took up a large part of the screen).  REally hard to position when you cant see where you need to go.

**Do you have an error log of what happened?**

I just installed bugsack and bugtracker so I hope to be able to include details if it is still happening.  I saw an update for Mythic Tindral went out so i hope that it has solved the issue.

**To Reproduce**
Start the Tindral encounter in Heroic mode - several guild members reported the issue.

**Screenshots**

will do if it happens tonight.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I haven't.  If it happens tonight I will try this

**Which version of DeadlyBossMods are you using?**

current - it updated yesterday.

**Was it working in a previous version? If yes, which was the last good one?**

It started this Tuesday after 10.2.5

**Additional context**
I wish I had more detail for you

**Comment by mic-dev-84** [comment] 2024-01-18 19:25
We had the same issue yesterday 22:00 CEST with several raid-members

**Comment by MysticalOS** [comment] 2024-01-18 22:31
Did you not update DBM last night? This issue has already been fixed and an emergency update was even released to fix it

**Comment by wnuko** [comment] 2024-01-19 00:26
I had the same issue as reported and managed to take a screenshot of the error (for later analysis).
`DBM-Core.lua:6397`
Looking at the _emergency update_ fix, I'd say the problem is fixed now. (Though, I will not be able to test it until next week.)

**Comment by 1Drome** [comment] 2024-01-19 00:32
I raid tuesday and thursday so didnt run across it yesterday.  I looked at the change logs and the issues here and didn't see itmention of it so I figured I would report it.  Thank you for all the hard work you do - its a great MOD.

**Comment by mic-dev-84** [comment] 2024-01-19 00:37
issue is solved with the latest update

**Comment by MysticalOS** [comment] 2024-01-19 00:55
For those curious, this was the issue/fix
https://github.com/DeadlyBossMods/DBM-Unified/commit/31ea200200c4b2d5ec69a8131ffa9ad66890d3d9

**Comment by 1Drome** [comment] 2024-01-19 01:38
Worked great - Thanks again!

**Closed** 2024-02-04 10:50 UTC
Labels: duplicate
