### ISSUE TITLE
method raid tool pull timers not detected by DBM

### ISSUE THREAD

**Issue by Gregoronsen** [DeadlyBossMods/DBM-Retail#923] opened 2023-08-17 00:19 UTC
prior to 10.1.23 using method raid tools' pull timers would show a DBM pull timer, does not anymore

**Do you have an error log of what happened?**
no

**To Reproduce**
just doesnt work on 10.1.23, works on 10.1.21

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of DeadlyBossMods are you using?**
10.1.23
**Was it working in a previous version? If yes, which was the last good one?**
10.1.21

**Comment by MysticalOS** [comment] 2023-08-17 02:23
Duplicate of https://github.com/DeadlyBossMods/DBM-Retail/issues/922

**Closed by MysticalOS** 2023-08-17 02:23 UTC
