### ISSUE TITLE
Base UI Countdown broken?

### ISSUE THREAD

**Issue by StatmanHellscream** [DeadlyBossMods/DBM-Retail#925] opened 2023-08-23 04:17 UTC
**Describe the bug**
DBM-10.1.23-12 and beyond disable or block the in-game countdown timer button from the group/raid flyout menu and the "/countdown X" command. Pressing the button, or typing the command, gives no numbers, no countdown sound, and group members do not see the countdown either.

Note this is not the DBM Pull timer, this is the base game UI and "/countdown" countdown timers that no longer work for me.

**To Reproduce**
Form a normal party or raid, 
open the party/raid flyout menu on the left
Press the Countdown button
-nothing happens

or, type in "/countdown X", where X is a number of seconds like 5 or 10,
-nothing happens

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, tested with only DBM, as well as tested reinstalling older DBMs only to get the functionality back.

**Which version of DeadlyBossMods are you using?**
DBM-10.1.23-12 up to current DBM-10.1.24-2 have this broken or removed

**Was it working in a previous version? If yes, which was the last good one?**
DBM-10.1.23-11 and before worked and still work after re-installing old versions to test

**Comment by MysticalOS** [comment] 2023-08-23 04:40
Because the built in /countdown feature has continued to subpar and insecure, both DBM and BW are intentionally breaking it now so users are forced to use more reliable countdowns provided by DBM or Bigwigs pull timer instead.

the built in /countdown feature has following problems:
Doesn't include sender (which we both see as most insecure thing about it since it's ripe for trolling/abuse)
Doesn't support classic (which makes it impossible to implement any kind of actual useful interoperation with feature in DBM or BW)
Doesn't support intelligent permissions checks such as tank roles in group finder dungeons even if tank isn't "group leader" (which again is problematic because if a tank can't send a pull timer in queued content, it kinda renders /countdown useless)

So going forward, we plan to replace it with our own pull timers. It's sad really because we had a hope it'd be other way around (that it'd be good enough to replace ours, or rather we'd simply both use countdown and simply add our audios and visual timers to it).

The intended behavior though is when you do /countdown it's supposed to send a DBM (or BW if using their mod) timer instead. If it's doing nothing then that's a bug in DBM that should be fixed. It shouldn't do nothing, it should send a DBM pull timer if using DBM and a BW timer if using BW.

But, TL/DR, the blizzard one being suppressed is intentional because it's insecure and feature lacking and if user has DBM or BW installed they should be using that instead. When my computer is done being dumb I'll get back in wow and see why it's not sending a DBM timer in place of /countdown though, cause it definitely shouldn't just be doing nothing.

**Comment by MysticalOS** [comment] 2023-08-23 06:19
https://github.com/DeadlyBossMods/DBM-Unified/commit/f75671c93917d9c3bf75460b2f8a1390e33b5ce7 should fix it not sending a DBM timer, it will now.

**Comment by StatmanHellscream** [comment] 2023-08-23 06:23
all good now, thanks for the write-up/explaination, and quick fix.

**Closed** 2023-08-23 06:23 UTC

**Comment by chipzz** [comment] 2023-08-27 17:20
Please revert this.
I don't want to use /dbm pull, because I can not rely on everyone having DBM installed. People may be using BigWigs instead. /countdown is superior in the regard that it is supported for everyone.
Or you could turn this into an option.
Intentionally breaking stock UI is in very very bad taste IMO.
