### ISSUE TITLE
missing DBM-Party-WotLK folder for DBM-3.4.38

### ISSUE THREAD

**Issue by OleksandrDavydovGG** [DeadlyBossMods/DBM-Retail#882] opened 2023-04-14 10:00 UTC
DBM doesn't work in the dungeons of the Lich King for the classic versions of WoW Wrath of the Lich King.
Missing DBM-Party-WotLK folder for DBM-3.4.38

**Comment by MysticalOS** [comment] 2023-04-14 10:01
duplicate of https://github.com/DeadlyBossMods/DBM-WoTLKC/issues/18 so closing this one

**Closed by MysticalOS** 2023-04-14 10:01 UTC
