### ISSUE TITLE
Script Error entering Halls of Infusion DF dungeon

### ISSUE THREAD

**Issue by emmetotter** [DeadlyBossMods/DBM-Retail#832] opened 2022-12-06 02:33 UTC
**Describe the bug**
Script Error initially entering the Halls of Infusion

**Do you have an error log of what happened?**
Message: ...ragonflight/HallsofInfusion/HallsofInfusionTrash.lua:10: attempt to perform arithmetic on a string value
Time: Mon Dec  5 19:13:41 2022
Count: 1
Stack: ...ragonflight/HallsofInfusion/HallsofInfusionTrash.lua:10: attempt to perform arithmetic on a string value
[string "@Interface/AddOns/DBM-Party-Dragonflight/HallsofInfusion/HallsofInfusionTrash.lua"]:10: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3548: in function `LoadMod'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3491: in function `LoadModsOnDemand'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:3429: in function `func'
[string "@Interface/AddOns/DBM-Core/modules/Scheduler.lua"]:171: in function <Interface/AddOns/DBM-Core/modules/Scheduler.lua:162>

Locals: mod = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 SyncThreshold = 8
 modId = "DBM-Party-Dragonflight"
 groupSpells = <table> {
 }
 zones = <table> {
 }
 revision = 20221204033441
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "HallsofInfusionTrash"
 isTrashMod = true
 addon = <table> {
 }
 specwarns = <table> {
 }
 groupOptions = <table> {
 }
 iconRestore = <table> {
 }
 optionCategories = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 subTab = 8
}
L = <table> {
 name = "Halls of Infusion Trash"
}
(*temporary) = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1094
(*temporary) = <table> {
 timers = <table> {
 }
 categorySort = <table> {
 }
 SyncThreshold = 8
 modId = "DBM-Party-Dragonflight"
 groupSpells = <table> {
 }
 zones = <table> {
 }
 revision = 20221204033441
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "HallsofInfusionTrash"
 isTrashMod = true
 addon = <table> {
 }
 specwarns = <table> {
 }
 groupOptions = <table> {
 }
 iconRestore = <table> {
 }
 optionCategories = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 subTab = 8
}
(*temporary) = "SPELL_CAST_START 390290 374080 375351 375348 375327 375384 374563"
(*temporary) = "SPELL_AURA_APPLIED 374724"
(*temporary) = 20221204033441
(*temporary) = "number"
(*temporary) = 4
(*temporary) = 3
(*temporary) = 34
(*temporary) = 41
(*temporary) = 20221204033441
(*temporary) = 20220000000000
(*temporary) = 2022
(*temporary) = 12
(*temporary) = 4
(*temporary) = 3
(*temporary) = 34
(*temporary) = "attempt to perform arithmetic on a string value"

**To Reproduce**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.  Didn't experiment with enabling/disabling addons.

**Which version of DeadlyBossMods are you using?**  DBM-10.0.4-4-g92a0b3d.zip installed on December 5, 2022

**Was it working in a previous version? If yes, which was the last good one?**  Don't know.

**Comment by MysticalOS** [comment] 2022-12-06 02:33
duplicate of https://github.com/DeadlyBossMods/DBM-Retail/issues/831

**Closed by MysticalOS** 2022-12-06 02:33 UTC
