### ISSUE TITLE
Mythic kel'thuzad, soul reavers not getting marked during intermission

### ISSUE THREAD

**Issue by bgodbgg** [DeadlyBossMods/DBM-Retail#653] opened 2021-08-27 01:29 UTC
Not sure what to say, I can post screenshots, we clicked some buttons/disabled other marks and it marked X and square, but never marked skull.

**Comment by jazz836062** [comment] 2021-08-31 23:19
I plan on getting you a transcriptor log tonight for Mythic KT.  But BW is currently marking the adds.  Is that going to mess with the transcriptor?

**Comment by MysticalOS** [comment] 2021-08-31 23:22
it might. DBM force disables marking if BW is installed. So as long as YOU aren't using BW and are running DBM when doing the debug log, it should be fine.

Btw any time markers weren't working, were there any BW players in raid setting markers? they do NOT use same logic when marking so the missing mark could have just been bw conflict/moving icon and causing an unmarked to happen.

**Comment by jazz836062** [comment] 2021-08-31 23:32
I specifically demoted everyone except myself, only running DBM and the marks did not go out.  I don't run both, I only run DBM.

**Comment by MysticalOS** [comment] 2021-08-31 23:34
and you were always in same phase as adds? not with the mini boss phase?

**Comment by jazz836062** [comment] 2021-08-31 23:34
Correct.  I am a tank and never go down.

**Comment by jazz836062** [comment] 2021-08-31 23:35
I was also Raid Leader (with no assistants) at the time of the test.

**Comment by jazz836062** [comment] 2021-09-01 01:42
Is the transcriptor a separate addon?

**Comment by QartemisT** [comment] 2021-09-01 01:48
Yes, you can find it here: https://www.curseforge.com/wow/addons/transcriptor

**Comment by jazz836062** [comment] 2021-09-01 01:50
That is what I grabbed.  Will Heroic work for your testing or does it need to be mythic?

**Comment by MysticalOS** [comment] 2021-09-01 01:51
Heroic would probably work if you can still control all variables.

**Comment by jazz836062** [comment] 2021-09-01 02:34
[Transcriptor.zip](https://github.com/DeadlyBossMods/DeadlyBossMods/files/7087813/Transcriptor.zip)
Here you go.

**Comment by MysticalOS** [comment] 2021-09-01 02:39
At least 3 people in raid had assist, and out of Roodon Thatguyagain and Allthatjazz, Allthatjazz was chosen as the designated icon setter for having lowest latency.

What can you tell me about these 3. which phase were they assigned, did any of them have BW installed?

**Comment by MysticalOS** [comment] 2021-09-01 02:55
Did you do `/dbm debuglevel 3` ? that might be why the debug doesn't have enough information.

**Comment by MysticalOS** [comment] 2021-09-01 03:50
I pushed a new alpha version of core that has much better debug and some bug fixes that may or may not be related to why KelThuzad marking isn't working, so I encourage you to grab latest alpha revision and test it in raid. Anyone else with assist is also encouraged to grab it.
This exact file (or newer)
https://www.curseforge.com/wow/addons/deadly-boss-mods/files/3445568

**Comment by jazz836062** [comment] 2021-09-01 13:22
I'll grab it and let you know.

**Comment by jazz836062** [comment] 2021-09-02 23:47
Tested last night and it worked for the first set of adds, but didn't mark any Soul Reavers the second time they spawned.

**Comment by MysticalOS** [comment] 2021-09-02 23:48
New transcriptor of last night?

**Comment by jazz836062** [comment] 2021-09-03 13:07
I didn't get a new transcriptor, and we managed to kill him so it will be a while before I can get you one.  I was the only one that had marking perms in the whole raid.

**Comment by mariof81** [comment] 2021-09-13 09:20
We had the same problems yesterday. Only one or two Soul Reavers were tetting marked.
After some trys I degraded other members with assist so I was the only one for marking.
Most times it marked X, sometimes square and out of 30 pulls +/- 1-2 times skull.
DBM Version was 9.1.12.

**Comment by MysticalOS** [comment] 2021-09-13 12:15
It's had a lot of code changes in development versions. At this point I'm only interested on if it's still broken in 9.1.13 alphas. The fixes need more testing.

**Comment by mariof81** [comment] 2021-09-13 12:33
Okay. I think you mean 9.1.12-24-ga0a6084? I'll installed it now and try it on the next progress evening on saturday

**Comment by MysticalOS** [comment] 2021-09-13 12:35
Much thanks, any feedback appreciated on that

**Comment by mariof81** [comment] 2021-09-19 08:13
I'm sorry to say the soul reaver marking is still not working for us.
On the first try only X and square were marked. On third pull none was marked. On the forth pull only square was used.
What I observed regarding soul shards marking during first four pull, this one was only using the skull mark instead of 5 symbols. 
Then we decided to not use the marking from dbm.

**Comment by MysticalOS** [comment] 2021-09-19 13:37
I'm starting to think there has to be some kind of blizzard GUID bug on this fight. it sounds like same bug as drestagath on 8.3 where the combat log had unique guids for the mobs but the nameplates did not, causing marking to be utterly useless (by GUID). This is something I cannot verify with combatlog alone and need someone that knows what they are doing to debug in the raid itself. I know BW marking does NOT use GUID based marking in this case since they aren't trying to honor combat log order. I really didn't want to do blind marking without guid matching because it means you HAVE to have a designated marker or there will be icon setting conflicts, which means bringing back the problem of "if that marker is out of range, or goes into phyl, there will be no marking" problem.

considering GUID marking Never works here though, it looks like I have to scrap it in both cases. Coding wise I cannot find any bugs so at this point it HAS to be blizzards fault though with mismatching/GUID duplication bug.

I'll apply the weaker icon marking style which will work but it will be slower and will only allow 1 icon marker ever (and won't be able to inteligently choose who that is, meaning if an assist in raid goes in phyl, there may be no marking at all)

**Comment by mariof81** [comment] 2021-09-19 13:43
These are Lines from the combat Logs; and there are the GUIDs in it:
9/18 20:10:09.631  SPELL_SUMMON,Creature-0-4246-2450-29558-175559-0000462747,"Kel'Thuzad",0xa48,0x0,Creature-0-4246-2450-29558-176973-0000462B83,"Unaufhaltsame MonstrositÃ¤t",0xa28,0x0,352092,"Marsch der Verlassenen",0x8
9/18 20:10:09.631  SPELL_SUMMON,Creature-0-4246-2450-29558-175559-0000462747,"Kel'Thuzad",0xa48,0x0,Creature-0-4246-2450-29558-176973-0000C62B83,"Unaufhaltsame MonstrositÃ¤t",0xa28,0x0,352092,"Marsch der Verlassenen",0x8
9/18 20:10:09.631  SPELL_SUMMON,Creature-0-4246-2450-29558-175559-0000462747,"Kel'Thuzad",0xa48,0x0,Creature-0-4246-2450-29558-176974-0000462B83,"SeelenhÃ¤scherin",0xa28,0x0,352094,"Marsch der Verlassenen",0x8
9/18 20:10:09.631  SPELL_SUMMON,Creature-0-4246-2450-29558-175559-0000462747,"Kel'Thuzad",0xa48,0x0,Creature-0-4246-2450-29558-176974-0000C62B83,"SeelenhÃ¤scherin",0xa28,0x0,352094,"Marsch der Verlassenen",0x8
9/18 20:10:09.631  SPELL_SUMMON,Creature-0-4246-2450-29558-175559-0000462747,"Kel'Thuzad",0xa48,0x0,Creature-0-4246-2450-29558-176974-0001462B83,"SeelenhÃ¤scherin",0xa28,0x0,352094,"Marsch der Verlassenen",0x8

I can help you with debug, what do I have to do?

**Comment by MysticalOS** [comment] 2021-09-19 13:45
The thing is seeing if all the nameplate guids matched and if they were all unique like combat log

instructions for debugging are already in this thread though, just look above.
Basically
1. enable dbm debug
2. Set debug level to 3
3. enable and run transcriptor for fight
4. share the transcriptor to see where it went wrong.

**Comment by mariof81** [comment] 2021-09-19 13:47
Enable DBM debug is only one time thing per session? Or before every fight like transcriptor enable/disable?

**Comment by MysticalOS** [comment] 2021-09-19 13:50
Debug stays enabled until disabled.

**Comment by MysticalOS** [comment] 2021-09-19 13:50
Alphas should work, but note i'm about to push a new one to fix shards

**Comment by mariof81** [comment] 2021-09-19 13:52
Okay. Will try it tonight, in about 4 hours und update beforehand.

**Comment by mariof81** [comment] 2021-09-19 21:17
[Transcriptor.zip](https://github.com/DeadlyBossMods/DBM-Retail/files/7192931/Transcriptor.zip)
Hey, I can confirm shards marking works now. Soul Reaver marking still has bugs, transcript from our progress as attachment. I don't know if I disabled assist for all other players or not. Boss is dead now so I can't test for some time.

Thanks for all your work that you put into dbm!

**Comment by MysticalOS** [comment] 2021-09-19 21:25
`"<581.21 20:12:58> [DBM_Debug] canSetIcons or allAllowed true for SetIconOnReaper#2", -- [36402]
			"<581.21 20:12:58> [DBM_Debug] Match found in mobUids, SHOULD be setting icon on boss3#2", -- [36403]
			"<581.21 20:12:58> [CLEU] SPELL_SUMMON#Creature-0-4242-2450-23737-175559-0000477CD6#Kel'Thuzad#Creature-0-4242-2450-23737-176974-0000477DAA#Seelenhäscherin#352094#Marsch der Verlassenen#nil#nil", -- [36404]
			"<581.21 20:12:58> [DBM_Debug] INSTANCE_ENCOUNTER_ENGAGE_UNIT event fired for zoneId2450#3", -- [36405]
			"<581.21 20:12:58> [INSTANCE_ENCOUNTER_ENGAGE_UNIT] Fake Args:#boss1#false#false#true#Kel'Thuzad#Creature-0-4242-2450-23737-175559-0000477CD6#elite#7631295#boss2#false#true#true#Überrest von Kel'Thuzad#Creature-0-4242-2450-23737-176929-0000477CD6#elite#6147808#boss3#false#false#false#Unbekannt#Creature-0-4242-2450-23737-176974-0000477DAA#normal#0#boss4#false#false#false#Unbekannt#Creature-0-4242-2450-23737-176974-0000C77DAA#normal#0#boss5#false#false#false#??#nil#normal#0#Real Args:", -- [36406]
			"<581.21 20:12:58> [DBM_Debug] canSetIcons or allAllowed true for SetIconOnReaper#2", -- [36407]
			"<581.21 20:12:58> [DBM_Debug] Match found in mobUids, SHOULD be setting icon on boss4#2", -- [36408]
			"<581.21 20:12:58> [CLEU] SPELL_SUMMON#Creature-0-4242-2450-23737-175559-0000477CD6#Kel'Thuzad#Creature-0-4242-2450-23737-176974-0000C77DAA#Seelenhäscherin#352094#Marsch der Verlassenen#nil#nil", -- [36409]
			"<581.22 20:12:58> [DBM_Debug] INSTANCE_ENCOUNTER_ENGAGE_UNIT event fired for zoneId2450#3", -- [36410]
			"<581.22 20:12:58> [INSTANCE_ENCOUNTER_ENGAGE_UNIT] Fake Args:#boss1#false#false#true#Kel'Thuzad#Creature-0-4242-2450-23737-175559-0000477CD6#elite#7631295#boss2#false#true#true#Überrest von Kel'Thuzad#Creature-0-4242-2450-23737-176929-0000477CD6#elite#6147808#boss3#false#false#false#Unbekannt#Creature-0-4242-2450-23737-176974-0000477DAA#normal#0#boss4#false#false#false#Unbekannt#Creature-0-4242-2450-23737-176974-0000C77DAA#normal#0#boss5#false#false#false#Unbekannt#Creature-0-4242-2450-23737-176974-0001477DAA#normal#0#Real Args:", -- [36411]
			"<581.22 20:12:58> [DBM_Debug] canSetIcons or allAllowed true for SetIconOnReaper#2", -- [36412]
			"<581.22 20:12:58> [DBM_Debug] Match found in mobUids, SHOULD be setting icon on boss5#2", -- [36413]
			"<581.22 20:12:58> [CLEU] SPELL_SUMMON#Creature-0-4242-2450-23737-175559-0000477CD6#Kel'Thuzad#Creature-0-4242-2450-23737-176974-0001477DAA#Seelenhäscherin#352094#Marsch der Verlassenen#nil#nil", -- [36414]`

Based on this it set icons on all 3 reapers who were boss3 boss4 and boss5

**Comment by mariof81** [comment] 2021-09-19 21:30
Well I do have Logs and VOD of it. At 20:12 no reaper was marked.

This is damage on cross (red) mark only in the try starting 20:10, on 20:12 no dmg on red mark, only in 2. intermission there is damage on red mark:
https://www.warcraftlogs.com/reports/LDfCcd2gbyQWvkm1#fight=2&phase=2&type=damage-done&pins=2%24Off%24%23244F4B%24expression%24target.marker%3D7&cutoff=0

**Comment by MysticalOS** [comment] 2021-09-19 21:31
and you can verify no one had bw marking enabled? if someone else was marking not the same targets then marks would be cleared/messed up.

**Comment by mariof81** [comment] 2021-09-19 21:33
You can use replay feature on this try and see that nothing is marked at ~ 2:10, only one mark at ~ 5:00 (20:15).
Only thing we used is marking 2 player with yellow and orange using method raid tools.

**Comment by mariof81** [comment] 2021-09-19 21:38
As far as I know, raid marking only works if someone has assist. No player with BW did have assist.
Btw. how can I turn on the option to show raid marking as chat message?

**Comment by MysticalOS** [comment] 2021-09-19 21:40
right click chat tab, choose options or filters or whatever it's called (out of game at moment) and  enable "raid targets icons" or whatever it's called then when someone sets icon it'll say in chat

x has set icon on y
just helps see where marks are coming from

**Comment by mariof81** [comment] 2021-09-19 21:45
Okay I understand. But I'm quite sure this would confirm that the only marks being set are those from me.
Is the marking soul reaver quite different then marking shards?

**Comment by MysticalOS** [comment] 2021-09-19 21:46
no, it's actually literally idenical

**Comment by MysticalOS** [comment] 2021-09-19 22:35
I think i finally see the problem, It's order of events. dbm is setting icons TOO fast. It's calling SetRaidTarget on the units using boss3, boss4, boss5, before IEEU has fired (it does fire in same milisecond right after). Because of order of operatoins being off here, SetRaidTarget would actually refuse to set the icon because technically boss unit Id doesn't exist until the boss frame is visible (after IEEU). That also explains why it was usually skull missing. the boss frames were more likely to be visible by the time icon 2 and 3 came up. I should be able to fix this by simply moving my code directly to IEEU instead of SPELL_SUMMON.

**Comment by MysticalOS** [comment] 2021-09-19 23:09
I pushed a new alpha with changed code considering above possible theory. If theory is right then it should just work now, if theory is wrong then 🤷‍♂️

**Comment by mariof81** [comment] 2021-09-20 05:29
Thanks for your investigation. I think I could try this on heroic too, even when there are only two adds?

**Comment by MysticalOS** [comment] 2021-09-22 23:10
Meant to get back sooner, but yes heroic should be good testing too. I'm confident we got issue this time but need to test to be sure before closing issue

**Comment by MysticalOS** [comment] 2021-10-03 01:37
Not heard back on results of testing, heroic or mythic. I'm confident delaying setting until IEEU should have been enough to work around issue of setting icons on "boss" unit Ids before they fully exist, but I'd still like confirmation before closing.

**Comment by mariof81** [comment] 2021-10-03 07:36
On our last heroic raid, soul shard marking worked.
For soul reaper I can't confirm 100%, I will have a look next week.

**Comment by mariof81** [comment] 2021-10-09 13:16
Heroic Soul Reaper marking did work with DBM 9.1.17-2-g8f3efe2

**Closed as completed** 2021-10-09 15:22 UTC
Labels: 🐛 Bug, question, Medium Priority

**Comment by jrowles** [comment] 2021-10-10 23:46
The reason it worked for them isn't because of kill time but instead Heroic vs Mythic.  Heroic only has 4 adds +  boss, so 5 boss units.  Mythic has 5 adds + boss, so 6 boss units.

**Comment by QartemisT** [comment] 2021-10-10 23:48
There's a new alpha build with rewritten and optimized icon code

**Comment by jrowles** [comment] 2021-10-10 23:49
> There's a new alpha build with rewritten and optimized icon code

I understand.  I'm the one that tested it (Justify).  I was just saying why it worked for the previous person.
