### ISSUE TITLE
DBM breaks built-in Blizzard countdown

### ISSUE THREAD

**Issue by chipzz** [DeadlyBossMods/DBM-Retail#926] opened 2023-08-27 17:11 UTC
I opened the Blizzard Raid UI, pressed the countdown button. I expected a countdown to start, but nothing happened at all.

No lua script errors, nothing in taint.log

1) Start a group in LFG
2) Open the Blizzard Raid UI, press the countdown button
3) Blizzard countdown doesn't happen

No Screenshot

DBM is the addon causing the issue. Everything works as expected when only disabling DBM

Using latest version from CurseForge for retail

It was working in a previous version of WoW, not sure if a new DBM version is causing the issue. It broke after the weekly maintenance on 2023/08/23.

**Comment by MysticalOS** [comment] 2023-08-28 03:06
duplicate of https://github.com/DeadlyBossMods/DBM-Retail/issues/925

**Closed by MysticalOS** 2023-08-28 03:06 UTC
